### ISSUE TITLE
Diagrama De Clases

### ISSUE THREAD

**Issue by Abraham890** [SistemasTecTlaxiaco/practica-de-diagrama-de-clases-tecno-power#1]
[Diagrama de clases_tecno-power.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-diagrama-de-clases-tecno-power/files/7819137/Diagrama.de.clases_tecno-power.pdf)

**Comment by salathiel1999** [comment]
Calificación-30%

**Comment by josealfredo79** [comment]
Bien hecho y revisado
